<?php
//装饰器模式  ---做文章修饰功能

class BaseArt
{
    protected $content;

    protected $art = null;

    public function __construct($content)
    {
        $this->content = $content;
    }

    public function decorator()
    {
        return $this->content;
    }
}

// 编辑文章摘要
class BianArt extends BaseArt
{
    public function __construct(BaseArt $art)
    {
        $this->art = $art;
        $this->decorator();
    }

    public function decorator()
    {
        // TODO: Change the autogenerated stub
        return $this->content = $this->art->decorator() . ' 小编加上文章摘要 ';
    }
}

$b = new BianArt(new BaseArt(' 天天向上 '));
echo $b->decorator(); echo "<br>";


// SEO 关键词
class SeoArt extends BaseArt
{
    public function __construct(BaseArt $art)
    {
        $this->art = $art;
        $this->decorator();
    }

    public function decorator()
    {
        // TODO: Change the autogenerated stub
        return $this->content = $this->art->decorator() . ' SEO关键词 ';
    }
}

$c = new SeoArt($b);
echo $c->decorator();echo "<br>";

$x = new BianArt(new SeoArt(new BaseArt("好好学习")));
echo $x->decorator();

